
import { Inter } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import Menu from "@/components/layouts/menu";
import Toolbars from "@/components/layouts/toolbar";
import {NextIntlClientProvider, useMessages} from 'next-intl';

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "MakeCvss",
//   description: "Generated by create next app",
// };

export default function LocaleLayout({ children, params: {locale} }) {

  const messages = useMessages();

  return (
    <html lang={locale} >
      <title>Projects chucholeo387</title>
      <meta name="description" content="Know my projects" />
      <body className="">
        <div className="flex h-full">
          <div className="min-w-48 w-80 min-h-screen shadow-2xl p-6 py-6 pt-8 hidden sm:block ">
              <div className="fixed min-w-56">
                <div className="font-bold ">
                  <Link href="/">
                    Chucholeo Projects
                  </Link>
                </div>
                <Menu/>
              </div> 
          </div>
          <div className="w-full  overflow-y-auto">
            <Toolbars/>
            <div className="p-2 px-4 ">
              {/* NextClientProvider es un componente que le da context al resto de los componente q se renderizan en children */}
              {/* Esto es para que puedan ser usado las tarducciones de la libreria de next-intl en los componentes que se renderizan del lado del cliente*/}
              <NextIntlClientProvider locale={locale} messages={messages}>
                {children}
              </NextIntlClientProvider> 
            </div>
          </div>      
        </div>
      </body>
    </html>
  );
}
